FORMAT: 1A
HOST: http://quick-cofee-dev.odin.pa.infobox.ru/

# QUICK-COFFEE: API администратора

Управление поставщиками, торговыми точками, сотрудниками и меню

##  Поставщики [/admin/supplier]


### Список [GET]
+ Request 

    + Headers
        
            Authorization: Basic ZGVmYXVsdDp7QTY3QjkyRjQtMUJDRi00OThDLTgwMTctMTA4NTg0MkIzNjUwfQ==

+ Response 200 (application/json; charset=utf-8)

            {
              "data": [
                {
                  "supplierid": 3,
                  "name": "У Тимура",
                  "description": "Мясо и зелень",
                  "sitelink": "",
                  "places": [
                    {
                      "placeid": 5,
                      "address": "ул. Богдана Титомира 11",
                      "latitude": 55.76844400,
                      "longitude": 37.65074300
                    },
                    {
                      "placeid": 6,
                      "address": "ул. Богдана Титомира 11",
                      "latitude": 55.76844400,
                      "longitude": 37.65074300
                    },
                    {
                      "placeid": 7,
                      "address": "ул. Богдана Титомира 11",
                      "latitude": 55.76844400,
                      "longitude": 37.65074300
                    }
                  ]
                },
                {
                  "supplierid": 7,
                  "name": "Traveller's coffee",
                  "description": "Сеть кофеен",
                  "sitelink": "www.travelerscoffee.ru",
                  "places": []
                },
                {
                  "supplierid": 11,
                  "name": "Я-Кафе",
                  "description": "Найдется все",
                  "sitelink": "http://ya.ru",
                  "places": []
                }
              ]
            }


### Добавить [POST]
+ Request 
        
    + Headers
        
            Authorization: Basic ZGVmYXVsdDp7QTY3QjkyRjQtMUJDRi00OThDLTgwMTctMTA4NTg0MkIzNjUwfQ==
            
    + Body

            {
                "name": "Z-Кафе",
                "description": "Найдется все",
                "sitelink": "http://ya.ru"
            }
            
+ Response 201 (application/json; charset=utf-8)

            {
              "data": {
                "supplierId": 14,
                "name": "Z-Кафе",
                "description": "Найдется все",
                "sitelink": "http://ya.ru"
              }
            }


##  Работа с поставщиком [/admin/supplier/{supplierId}]
+ Parameters
    + supplierId: `1` (number, required) - idenfifier


### Получить [GET]
+ Request 
        
    + Headers
        
            Authorization: Basic ZGVmYXVsdDp7QTY3QjkyRjQtMUJDRi00OThDLTgwMTctMTA4NTg0MkIzNjUwfQ==
            
+ Response 200 (application/json; charset=utf-8)

            {
              "data": {
                "supplierid": 3,
                "name": "У Тимура",
                "description": "Мясо и зелень",
                "sitelink": "",
                "places": [
                  {
                    "placeid": 5,
                    "address": "ул. Богдана Титомира 11",
                    "latitude": 55.76844400,
                    "longitude": 37.65074300
                  },
                  {
                    "placeid": 6,
                    "address": "ул. Богдана Титомира 11",
                    "latitude": 55.76844400,
                    "longitude": 37.65074300
                  },
                  {
                    "placeid": 7,
                    "address": "ул. Богдана Титомира 11",
                    "latitude": 55.76844400,
                    "longitude": 37.65074300
                  }
                ]
              }
            }


### Обновить [PUT]
+ Request 
        
    + Headers
        
            Authorization: Basic ZGVmYXVsdDp7QTY3QjkyRjQtMUJDRi00OThDLTgwMTctMTA4NTg0MkIzNjUwfQ==
            
    + Body

            {
              "name": "Кафе Куриные потроха Ext 2.0",
              "description": "Отборные куриные головы и лапки",
              "sitelink": "http://kokoko.ru"
            }
            
+ Response 200 (application/json; charset=utf-8)

            {
              "message": "OK"
            }


### Удалить [DELETE]
+ Request 
        
    + Headers
        
            Authorization: Basic ZGVmYXVsdDp7QTY3QjkyRjQtMUJDRi00OThDLTgwMTctMTA4NTg0MkIzNjUwfQ==
            
+ Response 200 (application/json; charset=utf-8)

            {
              "message": "OK"
            }


##  Торговые точки поставщика [/admin/supplier/{supplierId}/place]
+ Parameters
    + supplierId: `1` (number, required) - idenfifier


### Список [GET]
+ Request 
        
    + Headers
        
            Authorization: Basic ZGVmYXVsdDp7QTY3QjkyRjQtMUJDRi00OThDLTgwMTctMTA4NTg0MkIzNjUwfQ==
            
+ Response 200 (application/json; charset=utf-8)

            {
              "data": [
                {
                  "placeid": 5,
                  "address": "ул. Богдана Титомира 11",
                  "latitude": 55.76844400,
                  "longitude": 37.65074300
                },
                {
                  "placeid": 6,
                  "address": "ул. Богдана Титомира 11",
                  "latitude": 55.76844400,
                  "longitude": 37.65074300
                },
                {
                  "placeid": 7,
                  "address": "ул. Богдана Титомира 11",
                  "latitude": 55.76844400,
                  "longitude": 37.65074300
                }
              ]
            }

### Добавить [POST]
+ Request 
        
    + Headers
        
            Authorization: Basic ZGVmYXVsdDp7QTY3QjkyRjQtMUJDRi00OThDLTgwMTctMTA4NTg0MkIzNjUwfQ==
            
    + Body

            {  
               "name":"Кафе Куриные потроха Ext 2.0",
               "description":"Отборные куриные головы и лапки",
               "sitelink":"http://kokoko.com.ru"
            }
            
+ Response 201 (application/json; charset=utf-8)

            {
              "data": {
                "placeid": 15
              }
            }


##  Работа с торговой точкой [/admin/supplier/{supplierId}/place/{placeId}]
+ Parameters
    + supplierId: `1` (number, required) - idenfifier
    + placeId: `1` (number, required) - idenfifier


### Получить [GET]
+ Request 
        
    + Headers
        
            Authorization: Basic ZGVmYXVsdDp7QTY3QjkyRjQtMUJDRi00OThDLTgwMTctMTA4NTg0MkIzNjUwfQ==
            
+ Response 200 (application/json; charset=utf-8)

            {
              "data": {
                    "address": "ул. Богдана Титомира 11",
                    "latitude": 55.76844400,
                    "longitude": 37.65074300
                  }
            }


### Обновить [PUT]
+ Request 
        
    + Headers
        
            Authorization: Basic ZGVmYXVsdDp7QTY3QjkyRjQtMUJDRi00OThDLTgwMTctMTA4NTg0MkIzNjUwfQ==
            
    + Body

            {
              "address": "ул. Богдана Титомира 199",
              "latitude": 55.76844400,
              "longitude": 37.65074300
            }
            
+ Response 200 (application/json; charset=utf-8)

            {
              "message": "OK"
            }


### Удалить [DELETE]
+ Request 
        
    + Headers
        
            Authorization: Basic ZGVmYXVsdDp7QTY3QjkyRjQtMUJDRi00OThDLTgwMTctMTA4NTg0MkIzNjUwfQ==
            
+ Response 200 (application/json; charset=utf-8)

            {
              "message": "OK"
            }


##  Товары поставщика [/admin/supplier/{supplierId}/item]
+ Parameters
    + supplierId: `1` (number, required) - idenfifier


### Список [GET]
+ Request 
        
    + Headers
        
            Authorization: Basic ZGVmYXVsdDp7QTY3QjkyRjQtMUJDRi00OThDLTgwMTctMTA4NTg0MkIzNjUwfQ==
            
+ Response 200 (application/json; charset=utf-8)

            {
              "data": [
                {
                  "itemid": 2,
                  "name": "БигМак маленький",
                  "description": "Всё на булочке с кунжутом",
                  "price": 100
                },
                {
                  "itemid": 3,
                  "name": "name",
                  "description": "d",
                  "price": 1000
                },
                {
                  "itemid": 4,
                  "name": "БигМак маленький",
                  "description": "Всё на булочке с кунжутом",
                  "price": 500
                },
                {
                  "itemid": 1,
                  "name": "БигМак",
                  "description": "Всё на булочке с кунжутом",
                  "price": 10000
                }
              ]
            }

### Добавить [POST]
+ Request 
        
    + Headers
        
            Authorization: Basic ZGVmYXVsdDp7QTY3QjkyRjQtMUJDRi00OThDLTgwMTctMTA4NTg0MkIzNjUwfQ==
            
    + Body

            {
              "name": "БигМак маленький!",
              "description": "Всё на булочке с кунжутом",
              "price": 500
            }
            
+ Response 201 (application/json; charset=utf-8)

            {
              "data": {
                "itemId": 5,
                "name": "БигМак маленький!",
                "description": "Всё на булочке с кунжутом",
                "price": 500
              }
            }


##  Работа с товарами поставщика [/admin/supplier/{supplierId}/item/{itemId}]
+ Parameters
    + supplierId: `1` (number, required) - idenfifier
    + itemId: `1` (number, required) - idenfifier


### Получить [GET]
+ Request 
        
    + Headers
        
            Authorization: Basic ZGVmYXVsdDp7QTY3QjkyRjQtMUJDRi00OThDLTgwMTctMTA4NTg0MkIzNjUwfQ==
            
+ Response 200 (application/json; charset=utf-8)

            {
              "data": {
                "itemid": 1,
                "name": "БигМак",
                "description": "Всё на булочке с кунжутом",
                "price": 10000
              }
            }


### Обновить [PUT]
+ Request 
        
    + Headers
        
            Authorization: Basic ZGVmYXVsdDp7QTY3QjkyRjQtMUJDRi00OThDLTgwMTctMTA4NTg0MkIzNjUwfQ==
            
    + Body

            {
              "name": "БигМак",
              "description": "Всё на булочке с кунжутом",
              "price": 10000
            }
            
+ Response 200 (application/json; charset=utf-8)

            {
              "data": {
                "itemId": 0,
                "name": "БигМак",
                "description": "Всё на булочке с кунжутом",
                "price": 10000
              }
            }


### Удалить [DELETE]
+ Request 
        
    + Headers
        
            Authorization: Basic ZGVmYXVsdDp7QTY3QjkyRjQtMUJDRi00OThDLTgwMTctMTA4NTg0MkIzNjUwfQ==
            
+ Response 200 (application/json; charset=utf-8)

            {
              "message": "OK"
            }